# Generated by Django 4.2.20 on 2025-04-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bankQuiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprogress",
            name="user",
        ),
        migrations.AddField(
            model_name="playerprogress",
            name="anonymous_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="playerprogress",
            name="quizPoint",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizes",
                to="bankQuiz.level",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="question",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="bankQuiz.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="bankQuiz.level",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="option",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="bankQuiz.question",
            ),
        ),
    ]
