# Generated by Django 4.2.20 on 2025-04-11 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bankQuiz", "0002_remove_playerprogress_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprogress",
            name="anonymous_id",
        ),
        migrations.RemoveField(
            model_name="playerprogress",
            name="quizPoint",
        ),
        migrations.AddField(
            model_name="playerprogress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerprogress",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
