# Generated by Django 5.2 on 2025-04-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankQuiz", "0004_playerprogress_quizpoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
